### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by kingxdlol** [kingxdlol/Sample-programs#1]

**Comment by vinay72** [comment]
what is the issue here?

**Comment by kingxdlol** [comment]
Its a sample project for beginners, you guys can share your school time codes which you learned while learning the language.

the format for applying for a pull request is, simply create a new file at

<programming language>/<program_name>_<username>.<extension>
example: python/print-table_kingxdlol.py

This Repo is for encouraging beginners to code.

**Comment by Shogil** [comment]
C#
